# Exploration Methods
When you receive a CSV file from an external source, you'll want to get a feel for the data.

Let's import some data and then learn how to explore it.

In [4]:
# Setup
import os
import pandas as pd

# We use os.path.join because Windows uses a back slash (\) to separate directories
#  while others use a forward slash (/)
users_file_name = os.path.join('data', 'users.csv')
users_file_name

'data/users.csv'

In [5]:
os.getcwd()

'/Users/brianho/smart_sel_day1b/pandas'

## CSV File Exploration
If you want to take a peek at your CSV file, you could open it in an editor. 

Let's just use some standard Python to see the first couple lines of the file.

In [8]:
with open(users_file_name) as lines:
    print(lines.read())

,first_name,last_name,email,email_verified,signup_date,referral_count,balance
aaron,Aaron,Davis,aaron6348@gmail.com,True,2018-08-31,6,18.14
acook,Anthony,Cook,cook@gmail.com,True,2018-05-12,2,55.45
adam.saunders,Adam,Saunders,adam@gmail.com,False,2018-05-29,3,72.12
adrian,Adrian,Fang,adrian.fang@teamtreehouse.com,True,2018-04-28,3,30.01
adrian.blair,Adrian,Blair,adrian9335@gmail.com,True,2018-06-16,7,25.85
alan9443,Alan,Pope,pope@hotmail.com,True,2018-04-17,0,56.09
alexander7808,Alexander,Moore,alexander.moore@gmail.com,False,2018-03-27,2,87.71
alvarado,Denise,Alvarado,alvarado@hotmail.com,True,2018-09-07,6,26.72
alvarez,John,Alvarez,john4346@hotmail.com,True,2018-09-18,6,49.62
amanda,Amanda,Lynch,alynch@gmail.com,True,2018-09-18,2,43.76
amiller,Anne,Miller,miller@hotmail.com,False,2018-06-02,5,86.28
andersen,Mark,Andersen,mark.andersen@yahoo.com,True,2018-08-21,3,75.69
andrade,Melissa,Andrade,mandrade@yahoo.com,True,2018-01-06,3,83.22
andrew.alvarez,Andrew,Alvarez,aalvarez@hotmail.com,False,2018-08-01,0,81.66
andrew.wells,Andrew,Wells,andrew9976@yahoo.com,True,2018-06-13,5,76.07
andrew6216,Andrew,Bryan,andrew@gmail.com,True,2018-04-01,1,71.42
andrew6347,Andrew,Horton,andrew.horton@hotmail.com,True,2018-02-01,2,85.73
angela7209,Angela,Collins,collins5797@yahoo.com,True,2018-05-05,7,29.52
anthony1788,Anthony,Valdez,anthony@gmail.com,True,2018-06-30,5,70.7
anthony3761,Anthony,,anthony9581@gmail.com,True,2018-08-16,6,59.81
anthony576,Anthony,Lane,anthony@yahoo.com,True,2018-03-22,7,42.6
april9082,April,Santana,april.santana@hotmail.com,True,2018-08-14,2,53.87
ariley,Alexis,Riley,ariley@gmail.com,True,2018-05-10,2,89.22
arosario,Amanda,Rosario,amanda@yahoo.com,True,2018-01-29,1,76.19
atapia,Amy,Tapia,amy@hotmail.com,True,2018-02-06,5,67.96
austin,Austin,Ashley,austin5493@gmail.com,True,2018-03-12,7,70.38
austin486,Austin,Ward,ward@hotmail.com,True,2018-01-04,7,0.48
awhitney,Amanda,Whitney,whitney6923@yahoo.com,True,2018-04-06,2,30.85
awilliams,Amanda,Williams,williams4190@yahoo.com,True,2018-09-15,7,24.8
barnes,Mikayla,Barnes,mikayla.barnes@hotmail.com,True,2018-06-15,1,1.71
bernard,Dean,Bernard,dean.bernard@gmail.com,True,2018-02-03,6,45.67
bgreen,Brenda,Green,brenda.green@gmail.com,True,2018-02-17,7,47.89
bishop,Mason,Bishop,bishop@gmail.com,True,2018-02-14,5,4.59
blair4952,Nicole,Blair,nicole.blair@yahoo.com,True,2018-04-22,2,32.62
blankenship,April,Blankenship,blankenship11@gmail.com,True,2018-01-12,3,48.31
bowers9648,John,Bowers,bowers5600@hotmail.com,True,2018-06-19,4,36.92
bowman,Mary,Bowman,mary.bowman@sanchez.net,True,2018-04-13,3,54.21
boyer7005,Sara,Boyer,boyer8636@gmail.com,True,2018-07-31,0,91.41
bpowers,Bryce,Powers,bryce@yahoo.com,True,2018-02-28,2,17.99
bradley,Bradley,,bradley3941@henderson.com,True,2018-06-24,4,22.24
bradley3953,Bradley,Mills,mills6497@hotmail.com,True,2018-05-16,3,43.89
bradley7808,Bradley,,bradley8794@yahoo.com,True,2018-06-15,1,76.49
brandon,Brandon,King,bking@gmail.com,True,2018-02-15,5,56.25
brandon.gilbert,Brandon,Gilbert,brandon.gilbert@hotmail.com,True,2018-04-28,0,10.17
brenda,Brenda,,brenda@hotmail.com,True,2018-07-28,7,6.18
brett643,Brett,Sanchez,sanchez4831@hotmail.com,True,2018-01-03,6,30.8
brian.barnes,Brian,Barnes,brian.barnes@hotmail.com,True,2018-06-15,7,92.28
brian7426,Brian,Santiago,brian843@hotmail.com,True,2018-03-18,1,85.41
brooke2027,Brooke,,brooke6938@gmail.com,False,2018-05-23,0,7.22
brown,Kyle,Brown,brown9052@hotmail.com,True,2018-02-27,2,43.87
brown6798,Julia,Brown,julia.brown@bishop.com,True,2018-09-10,4,16.4
bryant,Darlene,Bryant,dbryant@yahoo.com,True,2018-07-19,0,36.91
bsmith,Benjamin,Smith,benjamin5212@hotmail.com,True,2018-08-05,3,15.77
burton6737,Darrell,Burton,burton@yahoo.com,True,2018-03-09,6,12.29
butler,Amy,Butler,amy4529@hotmail.com,True,2018-05-04,4,83.31
caleb,Caleb,Ellison,ellison@gmail.com,True,2018-04-17,1,36.84
calvin.perez,Calvin,Perez,cperez@gmail.com,True,2018-02-17,0,13.01
campbell1062,Amber,Campbell,amber.campbell@gmail.com,True,2018-01-10,3,35.66
campbell4312,Charlotte,Campbell,campbell@hotmail.com,True,2018-03-02,0,11.83
carl.fox,Carl,Fox,fox@hotmail.com,True,2018-04-29,6,19.13
cassandra,Cassandra,,cassandra9220@gmail.com,True,2018-05-03,5,78.9
chad.chen,Chad,Chen,chad.chen@hotmail.com,True,2018-02-09,7,7.5
charles,Charles,Tran,tran6961@yahoo.com,True,2018-02-20,6,40.79
charles559,Charles,Smith,smith@hotmail.com,True,2018-04-16,6,77.05
chorne,Christopher,Horne,horne@gmail.com,True,2018-03-28,4,28.49
christina.banks,Christina,Banks,cbanks@yahoo.com,True,2018-03-03,2,88.91
christine.brown,Christine,Brown,brown@hotmail.com,True,2018-05-05,4,67.24
christine2983,Christine,,christine3128@gmail.com,False,2018-05-23,5,94.02
christopher,Christopher,,christopher@gmail.com,True,2018-07-24,3,96.96
christopher5982,Christopher,Martin,martin@yahoo.com,False,2018-08-22,3,4.32
christopher6861,Christopher,Mitchell,mitchell@hotmail.com,False,2018-06-20,4,55.46
cjimenez,Charles,Jimenez,charles8775@gmail.com,True,2018-02-17,0,55.84
cjones,Carla,Jones,carla2889@gmail.com,True,2018-06-23,1,33.32
clark8139,Tara,Clark,clark@gmail.com,True,2018-01-26,6,93.23
clayton6074,Robert,Clayton,robert@gmail.com,True,2018-01-12,7,97.05
coleman,Amber,Coleman,amber1175@yahoo.com,True,2018-05-17,5,15.79
collin,Collin,,collin@gmail.com,False,2018-08-18,7,89.95
collins,Tyler,Collins,tyler.collins@hotmail.com,True,2018-08-16,6,94.69
colton,Colton,Burke,colton9297@yahoo.com,True,2018-02-12,6,57.98
conley,Courtney,Conley,conley140@gmail.com,True,2018-06-23,2,26.28
corey,Corey,Fuller,fuller8100@yahoo.com,True,2018-04-19,3,31.56
corey.ingram,Corey,Ingram,corey.ingram@gmail.com,True,2018-09-11,1,69.54
courtney9644,Courtney,Macias,courtney.macias@hotmail.com,True,2018-07-14,6,25.18
cox192,Eric,Cox,eric@hotmail.com,True,2018-06-24,3,0.05
crane203,Valerie,Crane,valerie7051@hotmail.com,True,2018-05-12,3,98.69
cross9059,Emily,Cross,emily8281@gmail.com,True,2018-01-07,7,83.62
cynthia5799,Cynthia,Castillo,ccastillo@moore.org,True,2018-03-09,0,91.83
dale,Dale,Salinas,dale@gmail.com,True,2018-04-01,2,19.61
dana.andrews,Dana,Andrews,dandrews@thomas.org,True,2018-09-16,4,54.68
danderson,David,Anderson,david@hotmail.com,True,2018-07-22,6,49.52
daniel,Daniel,Allen,allen@hotmail.com,False,2018-07-01,2,21.21
daniel.livingston,Daniel,Livingston,livingston794@yahoo.com,True,2018-06-22,5,29.66
daniel.williams,Daniel,Williams,williams6378@yahoo.com,True,2018-03-13,4,93.85
daniel1611,Daniel,Morales,morales8909@gmail.com,False,2018-05-15,7,60.66
danielle,Danielle,Salazar,danielle4662@drake.com,True,2018-03-21,3,45.09
darlene.adams,Darlene,Adams,adams@hotmail.com,True,2018-09-15,2,67.02
david,David,,david300@gmail.com,True,2018-03-28,0,59.74
david.barnett,David,Barnett,barnett462@hotmail.com,True,2018-02-21,2,46.88
david2796,David,Mcclure,david3888@hotmail.com,True,2018-09-16,5,37.6
david5498,David,Garcia,david2998@hotmail.com,True,2018-01-05,4,29.14
davis,Erica,Davis,erica@gmail.com,True,2018-06-08,2,53.52
davis9225,Laura,Davis,laura@hotmail.com,True,2018-03-19,3,51.81
davis9792,David,Davis,davis3883@hotmail.com,True,2018-01-04,4,36.9
dawn,Dawn,,dawn6718@hotmail.com,True,2018-03-02,2,72.63
dawn.juarez,Dawn,Juarez,dawn@hotmail.com,True,2018-04-13,1,16.38
dean,Lynn,Dean,dean@gmail.com,True,2018-05-22,3,17.45
dean2365,Brian,Dean,dean3892@hotmail.com,True,2018-01-08,6,8.5
debbie4918,Debbie,,debbie3109@hotmail.com,True,2018-02-09,7,73.63
debra,Debra,Frazier,frazier@yahoo.com,True,2018-06-01,1,80.71
decker1985,Robert,Decker,robert@yahoo.com,True,2018-04-04,7,92.55
dedwards,Deborah,Edwards,deborah@hotmail.com,False,2018-01-13,0,25.63
denise3770,Denise,Cabrera,cabrera@hotmail.com,False,2018-07-21,1,95.08
dennis,Trevor,Dennis,dennis@gmail.com,True,2018-04-29,2,10.04
dennis4593,Ann,Dennis,ann.dennis@christensen.com,True,2018-04-23,6,79.24
diana,Diana,Wagner,wagner8014@gmail.com,True,2018-01-15,4,19.45
diana1995,Diana,Gregory,gregory@gmail.com,True,2018-03-22,4,51.81
diane4652,Diane,,diane9705@yahoo.com,False,2018-08-17,1,62.05
donald1420,Donald,,donald1129@gmail.com,True,2018-08-24,2,74.58
donald3362,Donald,Kennedy,donald@small.biz,False,2018-04-01,2,81.06
donna1922,Donna,Castillo,donna.castillo@hotmail.com,True,2018-02-18,7,77.79
dustin.fowler,Dustin,Fowler,dustin@yahoo.com,True,2018-04-09,2,37.8
ebryant,Erik,Bryant,bryant@yahoo.com,True,2018-07-21,6,31.49
edward1527,Edward,,edward1672@yahoo.com,False,2018-03-07,3,69.63
edwards,Michael,Edwards,edwards5456@gmail.com,True,2018-05-06,4,83.33
edwards8658,Alan,Edwards,alan8469@hotmail.com,False,2018-02-24,1,24.93
ehaney,Emily,Haney,haney@gmail.com,True,2018-06-12,3,64.65
eharding,Eric,Harding,eric1206@yahoo.com,True,2018-08-25,1,42.71
ehernandez,Elizabeth,Hernandez,elizabeth.hernandez@gmail.com,True,2018-08-21,1,69.17
ekidd,Elizabeth,Kidd,kidd7082@hotmail.com,True,2018-08-01,7,13.14
elaine,Elaine,,elaine@yahoo.com,False,2018-04-20,5,45.2
elang,Erica,Lang,lang@gmail.com,True,2018-03-24,2,77.66
elizabeth,Elizabeth,Johnson,johnson913@yahoo.com,True,2018-02-20,1,77.91
emily,Emily,,emily7694@hotmail.com,True,2018-06-29,2,89.16
emily.anderson,Emily,Anderson,emily7106@gmail.com,True,2018-02-21,0,77.69
emily.lewis,Emily,Lewis,lewis8915@yahoo.com,True,2018-01-13,4,57.51
epeters,Emily,Peters,emily.peters@hotmail.com,True,2018-05-09,1,64.91
eric1415,Eric,Moon,emoon@yahoo.com,True,2018-04-25,6,39.16
erin,Erin,Robinson,erin@gmail.com,True,2018-06-17,7,70.32
erin4486,Erin,Wright,erin.wright@gmail.com,True,2018-05-31,5,76.18
eugene4448,Eugene,,eugene@gmail.com,True,2018-06-08,0,95.38
evelyn,Evelyn,Spencer,evelyn.spencer@yahoo.com,False,2018-07-29,6,6.25
fernandez,Theresa,Fernandez,theresa@gmail.com,True,2018-01-13,5,47.13
figueroa7283,Amy,Figueroa,figueroa@gmail.com,True,2018-07-27,3,36.5
fisher,Kenneth,Fisher,kenneth.fisher@ryan.net,True,2018-05-11,0,88.87
fitzgerald,William,Fitzgerald,wfitzgerald@pham-nguyen.com,True,2018-05-18,0,39.04
flores,Catherine,Flores,catherine346@oneal-roberts.info,True,2018-05-01,0,3.97
fox,David,Fox,fox@yahoo.com,True,2018-09-05,7,86.65
francis.hernandez,Francis,Hernandez,hernandez5650@hotmail.com,True,2018-02-12,3,28.44
freeman,Tamara,Freeman,tfreeman@yahoo.com,True,2018-04-22,7,51.72
fuentes,Alexander,Fuentes,alexander1368@gmail.com,True,2018-08-03,0,86.57
fuller3354,Nicole,Fuller,fuller@hotmail.com,False,2018-04-08,7,14.4
gail2190,Gail,Klein,gklein@yahoo.com,True,2018-08-17,4,48.7
gail7896,Gail,Clarke,clarke@gmail.com,True,2018-05-05,1,67.14
gary.mitchell,Gary,Mitchell,mitchell1601@davidson-wilson.com,False,2018-04-08,4,76.19
gerald.bryant,Gerald,Bryant,gerald.bryant@yahoo.com,True,2018-04-15,5,87.08
gibson9198,Jason,Gibson,jason4132@yahoo.com,True,2018-04-12,6,85.34
glen9827,Glen,Hawkins,glen8942@gmail.com,True,2018-02-02,5,27.72
grace7647,Grace,Payne,grace546@yahoo.com,True,2018-03-14,5,38.41
graham,Christopher,Graham,cgraham@hotmail.com,True,2018-07-06,3,18.18
grant1643,Jay,Grant,grant3970@hotmail.com,True,2018-01-25,7,3.01
greg5920,Greg,Kelley,greg1612@gmail.com,True,2018-01-02,6,29.16
gregory.blackwell,Gregory,Blackwell,gblackwell@frost-white.com,True,2018-01-10,3,63.14
gregory.rios,Gregory,Rios,gregory@gmail.com,True,2018-01-13,4,16.42
gregory7148,Jon,Gregory,gregory@keller-moran.net,True,2018-01-11,6,15.62
gregory9829,Gregory,Webb,gregory.webb@yahoo.com,True,2018-09-01,5,68.07
griffin4992,Kaitlin,Griffin,kaitlin.griffin@yahoo.com,True,2018-03-10,7,22.68
gstevens,Gabriella,Stevens,gabriella@gmail.com,False,2018-05-10,6,3.64
guzman4000,Ronald,Guzman,rguzman@gmail.com,True,2018-07-10,4,50.26
hall,George,Hall,hall@gmail.com,True,2018-03-14,3,85.4
hamilton,Douglas,Hamilton,hamilton6279@gmail.com,True,2018-06-30,1,58.98
hamilton4258,Mary,Hamilton,hamilton@yahoo.com,True,2018-03-30,4,72.44
harmon,Justin,Harmon,justin.harmon@hotmail.com,False,2018-04-12,4,91.87
harold,Harold,Willis,willis9328@yahoo.com,False,2018-05-07,1,6.0
harris7556,Kelli,Harris,kharris@gmail.com,True,2018-06-18,0,53.44
hart24,Teresa,Hart,teresa778@lucas.biz,False,2018-05-18,4,16.69
hayes2585,Daniel,Hayes,dhayes@gmail.com,True,2018-05-10,7,22.64
hdeleon,Hannah,Deleon,hannah@yahoo.com,True,2018-09-12,6,48.93
heather,Heather,Ray,hray@yahoo.com,True,2018-05-14,5,41.65
heather.wade,Heather,Wade,heather.wade@yahoo.com,True,2018-09-25,0,45.95
hector,Hector,Bowers,hbowers@hotmail.com,True,2018-07-09,0,21.24
helen5691,Helen,Simmons,simmons695@gmail.com,True,2018-03-02,3,93.83
henry,Steven,Henry,steven.henry@gmail.com,True,2018-03-07,1,12.58
henry4707,Nancy,Henry,nancy.henry@gmail.com,True,2018-03-02,3,73.17
higgins,Duane,Higgins,higgins@gmail.com,True,2018-04-03,5,62.12
hmiller,Howard,Miller,howard6112@yahoo.com,True,2018-04-25,6,64.03
holden4580,Jason,Holden,holden@gmail.com,True,2018-01-17,3,7.95
hoover4302,Michelle,Hoover,mhoover@hotmail.com,True,2018-02-09,0,37.38
hunt3408,Ethan,Hunt,hunt7143@gmail.com,False,2018-06-23,3,62.81
isabella,Isabella,Golden,isabella@perez-schultz.net,False,2018-07-24,5,65.71
jackson4431,Melissa,Jackson,jackson@gmail.com,True,2018-02-06,7,69.32
jacob,Jacob,Rose,rose@yahoo.com,True,2018-07-15,4,2.85
jacob.davis,Jacob,Davis,jdavis@gmail.com,False,2018-09-16,0,95.7
jaime6887,Jaime,Johnson,johnson@garcia-contreras.org,False,2018-01-19,4,81.6
james,James,Nichols,nichols@ramirez.com,False,2018-09-06,5,88.7
janet.williams,Janet,Williams,janet9480@hotmail.com,True,2018-05-31,0,71.53
jason,Jason,Nguyen,nguyen7758@yahoo.com,True,2018-04-30,1,60.4
jason4651,Jason,Parks,jason@yahoo.com,True,2018-09-03,3,40.76
jason7792,Jason,Holland,jholland@hotmail.com,False,2018-01-18,0,22.37
jbarker,Joe,Barker,joe@yahoo.com,False,2018-08-12,3,68.91
jcastaneda,Joshua,Castaneda,jcastaneda@yahoo.com,False,2018-05-06,7,53.54
jcoleman,Jason,Coleman,jason3300@gmail.com,True,2018-05-18,7,59.62
jcordova,Jennifer,Cordova,jcordova@hotmail.com,True,2018-02-27,0,31.72
jdiaz,Jay,Diaz,jdiaz@yahoo.com,False,2018-05-28,4,25.43
jeffrey,Jeffrey,Stewart,stewart7222@hotmail.com,True,2018-01-02,0,40.58
jennifer,Jennifer,Dean,jdean@davis-warren.com,True,2018-04-26,6,70.26
jennifer.hebert,Jennifer,Hebert,jennifer.hebert@yahoo.com,True,2018-07-24,5,16.27
jennifer.hendrix,Jennifer,Hendrix,hendrix1706@gmail.com,True,2018-01-15,0,37.2
jennifer.walker,Jennifer,Walker,walker6745@yahoo.com,False,2018-03-18,0,60.79
jennifer.wong,Jennifer,Wong,jwong@yahoo.com,True,2018-07-03,7,95.1
jennifer4743,Jennifer,Carter,jennifer.carter@gmail.com,True,2018-08-28,6,33.33
jensen7832,Steven,Jensen,steven.jensen@hotmail.com,True,2018-05-20,3,22.04
jeremy1104,Jeremy,Warren,jwarren@hotmail.com,True,2018-04-01,0,74.38
jerome.sims,Jerome,Sims,sims141@gmail.com,True,2018-09-13,7,34.31
jerry,Jerry,Mathis,jmathis@hotmail.com,True,2018-04-15,4,8.75
jessica,Jessica,,jessica@gmail.com,True,2018-06-14,2,23.09
jessica3924,Jessica,Preston,preston5688@yahoo.com,True,2018-09-04,3,42.68
jesus9614,Jesus,Johnson,johnson6528@gmail.com,True,2018-07-12,6,31.75
jgonzalez,Jenny,Gonzalez,jenny.gonzalez@hotmail.com,True,2018-06-03,1,0.59
jholloway,Julia,Holloway,julia9698@gmail.com,False,2018-09-08,6,16.27
jlong,Jessica,Long,jessica7275@gmail.com,True,2018-07-11,3,63.12
joel8826,Joel,Gates,joel516@hotmail.com,False,2018-03-05,4,71.6
john,John,,john@hotmail.com,True,2018-09-24,3,84.67
john.hardy,John,Hardy,hardy@gmail.com,True,2018-03-02,1,51.57
john.smith,John,Smith,john.smith@hotmail.com,True,2018-06-24,4,21.01
john6967,John,Vance,jvance@yahoo.com,True,2018-06-24,0,0.42
johnson,Brian,Johnson,johnson@hotmail.com,True,2018-09-11,7,12.23
johnson3004,Donald,Johnson,donald.johnson@gmail.com,True,2018-03-03,0,38.51
johnston2281,Nicholas,Johnston,njohnston@yahoo.com,True,2018-07-08,0,9.22
jonathan5101,Jonathan,Hayes,hayes1910@yahoo.com,True,2018-09-03,1,65.5
jones,Erin,Jones,erin.jones@yahoo.com,True,2018-01-25,2,86.66
jones5796,Katherine,Jones,jones@yahoo.com,True,2018-04-11,1,6.41
jordan5739,Jordan,Clayton,clayton@gmail.com,True,2018-06-26,1,81.47
jose.moreno,Jose,Moreno,jose@hotmail.com,True,2018-04-10,5,73.64
joseph.lopez,Joseph,Lopez,joseph@gmail.com,True,2018-08-12,6,65.99
joseph2431,Joseph,Harris,joseph@gmail.com,True,2018-03-07,5,95.47
joshua.henry,Joshua,Henry,joshua@hotmail.com,True,2018-01-05,2,80.03
joshua3747,Joshua,,joshua@hotmail.com,True,2018-05-22,0,11.7
joshua9690,Joshua,White,jwhite@hotmail.com,False,2018-03-27,7,47.31
jramos,Joshua,Ramos,joshua@yahoo.com,True,2018-07-10,6,75.56
jramsey,Jeremy,Ramsey,jeremy.ramsey@gmail.com,True,2018-02-18,5,58.74
jreeves,Jill,Reeves,reeves4581@yahoo.com,True,2018-07-27,2,56.56
jserrano,Jillian,Serrano,jillian@yahoo.com,True,2018-06-12,5,41.25
jstewart,Juan,Stewart,stewart@yahoo.com,True,2018-08-15,4,87.53
kallen,Kathy,Allen,kathy@hotmail.com,False,2018-02-20,1,43.72
kara,Kara,Ortega,kara9172@hotmail.com,True,2018-03-22,2,9.17
karen.snow,Karen,Snow,ksnow@yahoo.com,True,2018-05-06,2,99.38
katherine,Katherine,,katherine@yahoo.com,False,2018-01-26,3,59.06
kathy,Kathy,,kathy@gmail.com,False,2018-04-30,0,8.9
katrina.ingram,Katrina,Ingram,kingram@harris.com,True,2018-02-18,7,27.4
keith,Keith,Mercado,keith.mercado@yahoo.com,True,2018-05-21,2,0.85
keith2323,Keith,Lewis,keith.lewis@yahoo.com,True,2018-03-08,2,79.86
kelly5683,Kelly,Welch,kelly@hotmail.com,True,2018-09-20,5,9.24
kelly7722,Kelly,Knapp,knapp@yahoo.com,False,2018-05-20,0,73.62
kenneth.chambers,Kenneth,Chambers,kchambers@hotmail.com,True,2018-03-27,6,55.98
kent,Kayla,Kent,kent98@yahoo.com,True,2018-08-15,5,65.62
kevin,Kevin,Carter,kevin8487@ward-lopez.com,True,2018-03-17,5,6.68
kim1649,Stephen,Kim,stephen9674@gmail.com,True,2018-08-22,4,18.25
kimberly,Kimberly,,kimberly@yahoo.com,False,2018-01-06,5,54.73
kimberly.decker,Kimberly,Decker,kimberly5373@hotmail.com,False,2018-03-02,3,79.62
king,Billy,King,billy.king@hotmail.com,True,2018-05-29,4,98.8
king3246,Brittney,King,brittney@yahoo.com,True,2018-04-15,6,98.79
kirk,Kirk,Massey,kmassey@hotmail.com,True,2018-05-30,6,62.3
klein,Ashley,Klein,ashley@gmail.com,True,2018-03-06,3,13.65
kpratt,Kyle,Pratt,pratt@gmail.com,True,2018-03-17,2,4.51
kristen1581,Kristen,Thompson,kthompson@yahoo.com,False,2018-03-22,2,85.18
kristi7553,Kristi,Foster,kfoster@gmail.com,True,2018-06-08,0,40.14
kristina.miller,Kristina,Miller,miller@gmail.com,True,2018-03-08,7,90.82
krystal,Krystal,,krystal@hotmail.com,True,2018-05-30,3,46.92
kyle.gentry,Kyle,Gentry,kgentry@gmail.com,True,2018-08-30,6,42.36
lacey8987,Lacey,Ball,lacey5080@gmail.com,True,2018-01-02,0,93.49
laura,Laura,Wells,laura@yahoo.com,True,2018-06-01,3,36.74
lauren,Lauren,Aguilar,lauren.aguilar@summers.com,False,2018-05-31,4,69.9
lawrence1685,Derrick,Lawrence,lawrence7507@gmail.com,True,2018-08-05,5,47.29
lawrence3513,Katherine,Lawrence,lawrence@gmail.com,False,2018-06-23,2,76.63
lawson,Katherine,Lawson,katherine9625@gmail.com,True,2018-05-13,4,64.14
lcruz,Lauren,Cruz,lauren@gmail.com,True,2018-04-29,6,87.16
leah6255,Leah,Black,leah6754@willis.info,True,2018-01-13,1,43.67
lee,Catherine,Lee,catherine@hotmail.com,True,2018-05-22,5,73.1
lee3744,Timothy,Lee,lee@hotmail.com,False,2018-06-14,6,77.85
lewis8579,Christopher,Lewis,christopher.lewis@gmail.com,False,2018-02-24,6,5.68
lgregory,Leah,Gregory,gregory@gmail.com,True,2018-06-27,3,48.84
linda,Linda,,linda@hill-ferguson.info,False,2018-03-27,1,38.67
lindsay.coleman,Lindsay,Coleman,coleman7772@hotmail.com,True,2018-08-23,0,83.02
lisa,Lisa,Cook,lcook@hotmail.com,True,2018-06-14,2,34.82
lisa7840,Lisa,Anderson,lisa2797@hotmail.com,True,2018-07-24,4,91.46
lisa8780,Lisa,,lisa@hotmail.com,True,2018-05-03,3,36.82
lmoore,Lisa,Moore,moore1489@hotmail.com,True,2018-02-20,1,51.68
lowe,Albert,Lowe,albert.lowe@lopez.com,True,2018-01-13,1,60.9
lspencer,Laura,Spencer,spencer@yahoo.com,True,2018-07-07,6,17.59
lucero5925,Nicholas,Lucero,nicholas@gmail.com,True,2018-04-08,7,34.61
luis.brooks,Luis,Brooks,brooks7349@jones.com,True,2018-04-23,6,79.61
mackenzie,Mackenzie,Smith,smith3292@hotmail.com,True,2018-02-21,2,69.5
madison,Madison,Griffin,madison@gmail.com,True,2018-07-31,0,32.85
manning8686,Stephen,Manning,stephen@benson.com,True,2018-06-21,6,54.79
marcus.berry,Marcus,Berry,marcus.berry@stein.com,True,2018-05-14,3,6.81

Notice how the first line is a header row. It has column names in it. By default, it will be assumed that the first row is your header row.

Also note how the first column of that header row is empty...the values below in that first column appear to be usernames.  They are what we want for the index.

We can use the `index_col` parameter of the `pandas.read_csv` function.

In [26]:
# Create a new `DataFrame` and set the index to the first column
users = pd.read_csv(users_file_name, index_col = 0)

## Explore your imported DataFrame

A quick way to check and see if you got your CSV file read correctly is to use the [`DataFrame.head`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.head.html) method. This gives you the first **x** number of rows. The head method, by default, returns 5 records. You can specify the number you want as the first argument, for instance `users.head(10)` will return the first 10 rows.

In [27]:
users.head(20)

,first_name,last_name,email,email_verified,signup_date,referral_count,balance
aaron,Aaron,Davis,aaron6348@gmail.com,True,2018-08-31,6,18.14
acook,Anthony,Cook,cook@gmail.com,True,2018-05-12,2,55.45
adam.saunders,Adam,Saunders,adam@gmail.com,False,2018-05-29,3,72.12
adrian,Adrian,Fang,adrian.fang@teamtreehouse.com,True,2018-04-28,3,30.01
adrian.blair,Adrian,Blair,adrian9335@gmail.com,True,2018-06-16,7,25.85
alan9443,Alan,Pope,pope@hotmail.com,True,2018-04-17,0,56.09
alexander7808,Alexander,Moore,alexander.moore@gmail.com,False,2018-03-27,2,87.71
alvarado,Denise,Alvarado,alvarado@hotmail.com,True,2018-09-07,6,26.72
alvarez,John,Alvarez,john4346@hotmail.com,True,2018-09-18,6,49.62
amanda,Amanda,Lynch,alynch@gmail.com,True,2018-09-18,2,43.76
amiller,Anne,Miller,miller@hotmail.com,False,2018-06-02,5,86.28
andersen,Mark,Andersen,mark.andersen@yahoo.com,True,2018-08-21,3,75.69
andrade,Melissa,Andrade,mandrade@yahoo.com,True,2018-01-06,3,83.22
andrew.alvarez,Andrew,Alvarez,aalvarez@hotmail.com,False,2018-08-01,0,81.66
andrew.wells,Andrew,Wells,andrew9976@yahoo.com,True,2018-06-13,5,76.07
andrew6216,Andrew,Bryan,andrew@gmail.com,True,2018-04-01,1,71.42
andrew6347,Andrew,Horton,andrew.horton@hotmail.com,True,2018-02-01,2,85.73
angela7209,Angela,Collins,collins5797@yahoo.com,True,2018-05-05,7,29.52
anthony1788,Anthony,Valdez,anthony@gmail.com,True,2018-06-30,5,70.70
anthony3761,Anthony,NaN,anthony9581@gmail.com,True,2018-08-16,6,59.81

Nice! We got it.  So let's see how many rows we have.  There are a couple of ways.

In [14]:
# Pythonic approach still works
len(users)

475

*Side note*: This length call is quick. Under the covers this `DataFrame.__len__` call is actually performing a `len(df.index)`, counting the rows by using the index. You might see older code that uses the style of `len(df.index)` to get a count of rows. As of pandas version 0.11, `len(df)` is the same as `len(df.index)`.

The `DataFrame.shape` property works just like `np.array.shape` does. This is the length of each axis of your data frame, rows and columns.

In [15]:
users.shape

(475, 7)

### Exploring from a bird's eye view

#### Counts

The [`DataFrame.count`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.count.html) method will count up each column for how many non-empty values we have.

In [16]:
users.count()

first_name        475
last_name         430
email             475
email_verified    475
signup_date       475
referral_count    475
balance           475
dtype: int64

Most of our columns include values for each row, but looks like **last_name** has some missing ones.  The missing data will show up as `np.nan` -- NumPy's not a number -- in those records.


The `count` method is data missing aware.

Remember that a `DataFrame` has the ability to contain multiple data types or [`dtypes`](https://pandas.pydata.org/pandas-docs/stable/basics.html#basics-dtypes).

You can use the `DataFrame.dtypes` to see the `dtype` of each column.

#### Data types

In [17]:
users.dtypes

first_name         object
last_name          object
email              object
email_verified       bool
signup_date        object
referral_count      int64
balance           float64
dtype: object

As you can see, most of the data types of these columns were inferred, or assumed, correctly.  See how automatically **`email_verified`** is `bool`, **`referral_count`** is an integer, and **`balance`** a float. This happened when we used `pd.read_csv`. 

One thing to note though that the **`signup_date`** field is an `object` and not a `datetime`. You can convert these during or after import if you need to, and we'll do some of that later in this course.

#### Describe your data
The [`DataFrame.describe`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html) method is a great way to get a vibe for **all numeric data** in your `DataFrame`.  You'll notice only columns that have numeric data are returned, and ones with booleans or text, like **`email_verified`** and **`first_name`** are left out. 


You'll see lots of different aggregations.

In [21]:
users.describe()

       referral_count     balance
count      475.000000  475.000000
mean         3.429474   49.933263
std          2.281085   28.280448
min          0.000000    0.050000
25%          2.000000   25.305000
50%          3.000000   51.570000
75%          5.000000   74.480000
max          7.000000   99.900000

Most of these aggregations are available by themselves as well

In [22]:
# The mean or average
users.mean()

email_verified     0.818947
referral_count     3.429474
balance           49.933263
dtype: float64

In [23]:
# Standard deviation
users.std()

email_verified     0.385468
referral_count     2.281085
balance           28.280448
dtype: float64

In [28]:
# The minimum of each column
users.min()

first_name                       Aaron
email             aalvarez@hotmail.com
email_verified                   False
signup_date                 2018-01-01
referral_count                       0
balance                           0.05
dtype: object

In [29]:
# The maximum of each column
users.max()

first_name                Zachary
email             zneal@gmail.com
email_verified               True
signup_date            2018-09-25
referral_count                  7
balance                      99.9
dtype: object

Since columns are in reality a `Series` you can quickly access their counts of different values using the [`value_counts`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) method.

In [30]:
users['email_verified'].value_counts()

True     389
False     86
Name: email_verified, dtype: int64

By default the value counts are sorted descending, so the most frequent are at top.

In [32]:
# Most common first name
users['first_name'].value_counts().head(10)

Mark           11
David          10
Michael         9
Jennifer        7
Emily           7
William         7
Joshua          7
Christopher     7
Robert          7
Jason           6
Name: first_name, dtype: int64

### Rearranging your data
You can create a new `DataFrame` that is sorted by using the [`sort_values`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html) method.

Let's sort the DataFrame so that the user with the highest **`balance`** is at the top. By default, ascending order is assumed, you can change that by setting the `ascending` keyword argument to `False`.

In [33]:
users.sort_values(by='balance', ascending=False).head()

,first_name,last_name,email,email_verified,signup_date,referral_count,balance
twhite,Timothy,White,white5136@hotmail.com,True,2018-07-06,5,99.90
karen.snow,Karen,Snow,ksnow@yahoo.com,True,2018-05-06,2,99.38
king,Billy,King,billy.king@hotmail.com,True,2018-05-29,4,98.80
king3246,Brittney,King,brittney@yahoo.com,True,2018-04-15,6,98.79
crane203,Valerie,Crane,valerie7051@hotmail.com,True,2018-05-12,3,98.69

In [37]:
users = users.sort_values(by='balance', ascending=False)
users.head()

,first_name,last_name,email,email_verified,signup_date,referral_count,balance
twhite,Timothy,White,white5136@hotmail.com,True,2018-07-06,5,99.90
karen.snow,Karen,Snow,ksnow@yahoo.com,True,2018-05-06,2,99.38
king,Billy,King,billy.king@hotmail.com,True,2018-05-29,4,98.80
king3246,Brittney,King,brittney@yahoo.com,True,2018-04-15,6,98.79
crane203,Valerie,Crane,valerie7051@hotmail.com,True,2018-05-12,3,98.69

You'll notice that `sort_values` call actually created a new `DataFrame`. If you want to permanently change the sort from the default (sorted by index), you can pass `True` as an argument to the `inplace` keyword parameter.

In [40]:
# Sort first by last_name and then first_name. By default, np.nan show up at the end
users.sort_values(by=['last_name', 'first_name'])
# Sort order is now changed
users.head(20)

,first_name,last_name,email,email_verified,signup_date,referral_count,balance
twhite,Timothy,White,white5136@hotmail.com,True,2018-07-06,5,99.90
karen.snow,Karen,Snow,ksnow@yahoo.com,True,2018-05-06,2,99.38
king,Billy,King,billy.king@hotmail.com,True,2018-05-29,4,98.80
king3246,Brittney,King,brittney@yahoo.com,True,2018-04-15,6,98.79
crane203,Valerie,Crane,valerie7051@hotmail.com,True,2018-05-12,3,98.69

And if you want to **sort by the index (or label)**, like it was originally, you can use the `sort_index` method.

In [ ]:
users.sort_index(inplace=True)
users.head()